### ISSUE TITLE
ARM64 docker requirement

### ISSUE THREAD

**Issue by LinusJun** [TeddyNight/device_generic_goldfish#2]
麻烦请问能提供一个arm64的docker镜像吗？谢谢了

**Comment by TeddyNight** [comment]
抱歉，因为我本地机器性能不是很好，人在学校网络比较慢，总的来说，编译比较耗时，所以暂不提供arm64镜像。你可以尝试自己编译，配置好repo编译就行了，所有的修改我都放到github上了，包括这个仓库和vendor_redroid
